# Cấu hình chung
san_giao_dich_chinh: "okx"
cap_giao_dich:
- "BTC/USDT"

# Quản lý vốn
von_moi_lenh_usdt: 100
don_bay: 7 # là số trung vị của khoản đoàn vẩy từ 5 đến 9
max_lenh_cho_phep: 20
cat_lo_percent: 0.1   # Cắt lỗ 10%
chot_loi_percent: 0.15  # Chốt lời 15%
